apiVersion: v1
kind: Service
metadata:
  name: london-westend-trip
  namespace: london-westend-trip
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "london-westend-trip"
spec:
  type: ClusterIP
  selector:
    app: london-westend-trip
  ports:
    - port: 80
      targetPort: 8080
