apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-db-credentials
  namespace: forgejo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: forgejo-db-credentials
    template:
      type: kubernetes.io/basic-auth
      data:
        username: forgejo
        password: "{{ .db_password }}"
  data:
    - secretKey: db_password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: forgejo
        metadataPolicy: None
        property: db_password
