apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slownsteady-neon-secret
  namespace: slow-and-steady
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: slownsteady-neon-secret
  data:
    - secretKey: url
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: slownsteady_neon
        metadataPolicy: None
        property: url
