apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: alpine-escape
  namespace: argocd
spec:
  namespace: argocd
  applicationRefs:
    - namePattern: alpine-escape
      images:
        - alias: site
          imageName: ghcr.io/abelmeijberg/alpine-escape
          commonUpdateSettings:
            updateStrategy: newest-build
            allowTags: "regexp:^sha-"
            pullSecret: pullsecret:argocd/ghcr-pull-secret
