apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-escape
  namespace: alpine-escape
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine-escape
  template:
    metadata:
      labels:
        app: alpine-escape
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: alpine-escape
          image: ghcr.io/abelmeijberg/alpine-escape:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 64Mi
