apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: angine-site
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: site=ghcr.io/abelmeijberg/angine-site
    argocd-image-updater.argoproj.io/site.update-strategy: newest-build
    argocd-image-updater.argoproj.io/site.allow-tags: "regexp:^sha-"
    argocd-image-updater.argoproj.io/site.pull-secret: argocd/ghcr-pull-secret
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/AbelMeijberg/hetzner-cluster.git
    targetRevision: HEAD
    path: k8s/manifests/angine-site
  destination:
    server: https://kubernetes.default.svc
    namespace: angine-site
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
