apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argocd-image-updater
      targetRevision: "1.1.1"
      helm:
        valueFiles:
          - $values/k8s/values/argocd-image-updater.yaml
    - repoURL: https://github.com/AbelMeijberg/hetzner-cluster.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/AbelMeijberg/hetzner-cluster.git
      targetRevision: HEAD
      path: k8s/manifests/argocd-image-updater
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
