apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-secret-store
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/AbelMeijberg/hetzner-cluster.git
    targetRevision: HEAD
    path: k8s/manifests/cluster-secret-store
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
