apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: code.forgejo.org/forgejo-helm
      chart: forgejo
      targetRevision: "16.2.0"
      helm:
        valueFiles:
          - $values/k8s/values/forgejo.yaml
    - repoURL: https://github.com/AbelMeijberg/hetzner-cluster.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/AbelMeijberg/hetzner-cluster.git
      targetRevision: HEAD
      path: k8s/manifests/forgejo
  destination:
    server: https://kubernetes.default.svc
    namespace: forgejo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
